pipeline {
  agent any
  stages {
    stage('Clone Repository') {
      steps {
      git branch: 'main', url: 'https://github.com/<votre-utilisateur>/flask-github-jenkins.git'
      }
    }
  }
}
stage('Install Dependencies') {
  steps {
    sh '''
    python -m venv venv 
. venv/bin/activate
pip install -r requirements.txt
'''
}
}
